Added check library

diff --git a/docker-hub-image-size b/docker-hub-image-size
--- a/docker-hub-image-size
+++ b/docker-hub-image-size
@@ -12,10 +12,20 @@ page_size="${4:-200}"
 page_num=1
 while
 	response="$( curl -s "${docker_hub_endpoint}/${image}/tags/?page_size=${page_size}&page=${page_num}" )"
+	if [[ ! "$( echo "${response}" | jq -r '.count' )" =~ ^[0-9]+$ ]]
+	then
+		if [[ ${library_check} -ne 1 ]]
+		then
+			library_check=1
+			image="library/${image}"
+			page_num=1
+			continue
+		else
+			echo "ERROR: Image not found: ${image}" >&2 && exit
+		fi
+	fi
 	[[ "$( echo "${response}" | jq -r '.detail' )" == 'Not found' ]] \
 		&& echo "ERROR: Tag not found: ${tag}" >&2 && exit
-	[[ ! "$( echo "${response}" | jq -r '.count' )" =~ ^[0-9]+$ ]] \
-		&& echo "ERROR: Image not found: ${image}" >&2 && exit
 	[[ -z "$( echo "${response}" \
 		| jq -r ".results[] | select(.name==\"${tag}\") | .name" )" ]]
 do
